[2024-12-23T17:20:09.399+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.Random_Forest scheduled__2024-12-23T17:19:00+00:00 [queued]>
[2024-12-23T17:20:09.405+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.Random_Forest scheduled__2024-12-23T17:19:00+00:00 [queued]>
[2024-12-23T17:20:09.405+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-23T17:20:09.417+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Random_Forest> on 2024-12-23 17:19:00+00:00
[2024-12-23T17:20:09.423+0000] {standard_task_runner.py:60} INFO - Started process 12675 to run task
[2024-12-23T17:20:09.426+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'Random_Forest', 'scheduled__2024-12-23T17:19:00+00:00', '--job-id', '1000', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpvnx3idi9']
[2024-12-23T17:20:09.427+0000] {standard_task_runner.py:88} INFO - Job 1000: Subtask Random_Forest
[2024-12-23T17:20:09.438+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T17:20:09.465+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.Random_Forest scheduled__2024-12-23T17:19:00+00:00 [running]> on host b853fb0270cd
[2024-12-23T17:20:09.510+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='Random_Forest' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T17:19:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-23T17:19:00+00:00'
[2024-12-23T17:20:09.622+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-23T17:20:09.645+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-23T17:20:09.671+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-23T17:20:09.691+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-23T17:20:09.693+0000] {logging_mixin.py:188} INFO - The Negative Score with Random Forest  -57.613
[2024-12-23T17:20:09.693+0000] {python.py:201} INFO - Done. Returned value was: -57.61256076147719
[2024-12-23T17:20:09.712+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=Random_Forest, execution_date=20241223T171900, start_date=20241223T172009, end_date=20241223T172009
[2024-12-23T17:20:09.757+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-23T17:20:09.783+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
