[2024-12-24T13:22:10.165+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.Best_model scheduled__2024-12-24T13:21:00+00:00 [queued]>
[2024-12-24T13:22:10.171+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.Best_model scheduled__2024-12-24T13:21:00+00:00 [queued]>
[2024-12-24T13:22:10.171+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-24T13:22:10.181+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Best_model> on 2024-12-24 13:21:00+00:00
[2024-12-24T13:22:10.188+0000] {standard_task_runner.py:60} INFO - Started process 31885 to run task
[2024-12-24T13:22:10.192+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'Best_model', 'scheduled__2024-12-24T13:21:00+00:00', '--job-id', '2191', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpvmmol1mi']
[2024-12-24T13:22:10.192+0000] {standard_task_runner.py:88} INFO - Job 2191: Subtask Best_model
[2024-12-24T13:22:10.204+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-24T13:22:10.244+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.Best_model scheduled__2024-12-24T13:21:00+00:00 [running]> on host f70f31c57d74
[2024-12-24T13:22:10.332+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='Best_model' AIRFLOW_CTX_EXECUTION_DATE='2024-12-24T13:21:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-24T13:21:00+00:00'
[2024-12-24T13:22:10.378+0000] {logging_mixin.py:188} INFO - The best Model is  Random Forest, -60.038342555441155 
[2024-12-24T13:22:10.430+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-24T13:22:10.431+0000] {logging_mixin.py:188} INFO - RandomForestRegressor(n_estimators=10, oob_score=True, random_state=0) saved at  /app/clean_data/Random_forest_best_model.pickle
[2024-12-24T13:22:10.434+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-12-24T13:22:10.443+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=Best_model, execution_date=20241224T132100, start_date=20241224T132210, end_date=20241224T132210
[2024-12-24T13:22:10.483+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-24T13:22:10.507+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
