[2024-12-23T17:25:12.426+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.Random_Forest scheduled__2024-12-23T17:24:00+00:00 [queued]>
[2024-12-23T17:25:12.435+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.Random_Forest scheduled__2024-12-23T17:24:00+00:00 [queued]>
[2024-12-23T17:25:12.435+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2024-12-23T17:25:12.450+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): Random_Forest> on 2024-12-23 17:24:00+00:00
[2024-12-23T17:25:12.463+0000] {standard_task_runner.py:60} INFO - Started process 14266 to run task
[2024-12-23T17:25:12.481+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'Random_Forest', 'scheduled__2024-12-23T17:24:00+00:00', '--job-id', '1038', '--raw', '--subdir', 'DAGS_FOLDER/extract.py', '--cfg-path', '/tmp/tmpo5x85a9n']
[2024-12-23T17:25:12.482+0000] {standard_task_runner.py:88} INFO - Job 1038: Subtask Random_Forest
[2024-12-23T17:25:12.509+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-23T17:25:12.563+0000] {task_command.py:423} INFO - Running <TaskInstance: weather_dag.Random_Forest scheduled__2024-12-23T17:24:00+00:00 [running]> on host b853fb0270cd
[2024-12-23T17:25:12.680+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='thiernosidybah232@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='Random_Forest' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T17:24:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-23T17:24:00+00:00'
[2024-12-23T17:25:12.790+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-23T17:25:12.825+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-23T17:25:12.877+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-23T17:25:12.921+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/sklearn/ensemble/_forest.py:578: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable OOB estimates.
  warn(

[2024-12-23T17:25:12.924+0000] {logging_mixin.py:188} INFO - The Negative Score with Random Forest  -62.838
[2024-12-23T17:25:12.924+0000] {python.py:201} INFO - Done. Returned value was: -62.838436494667455
[2024-12-23T17:25:12.981+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=Random_Forest, execution_date=20241223T172400, start_date=20241223T172512, end_date=20241223T172512
[2024-12-23T17:25:13.002+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-12-23T17:25:13.018+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
